trigger:
  - main

pool: myagent
resources:
  pipelines:
    - pipeline: gitleak
      source: gitleak
      trigger:
        branches:
          include:
            - main

jobs:
  - job: BuildJob
    displayName: "Build and Trigger"
    steps:
      - script: echo "Running build process in Pipeline A..."
      - script: echo "Triggering Pipeline B..."
