trigger:
  - main

resources:
  pipelines:
    - pipeline: PipelineBTrigger
      source: gitleak

jobs:
  - job: BuildJob
    displayName: "Build and Trigger"
    steps:
      - script: echo "Running build process in Pipeline A..."
      - script: echo "Triggering Pipeline B..."
