trigger:
  - main # Trigger Pipeline A when changes are pushed to the 'main' branch
pool: myagent

jobs:
  - job: TriggerPipelineB
    displayName: "Trigger Pipeline B"
    steps:
      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: |
            # Define Azure DevOps REST API URL for triggering a pipeline
            $organization = "$(System.CollectionUri)"
            $project = "$(System.TeamProject)"
            $pipelineId = "<Pipeline_B_ID>"  # Replace with the ID of Pipeline B
            $url = "$organization/$project/_apis/pipelines/$pipelineId/runs?api-version=6.0-preview.1"

            # Define the request body
            $body = @{
                resources = @{
                    repositories = @{
                        self = @{
                            refName = "$(Build.SourceBranch)"  # Pass the branch being built
                        }
                    }
                }
            } | ConvertTo-Json -Depth 10

            # Trigger the pipeline
            $headers = @{
                "Authorization" = "Bearer $(System.AccessToken)"
                "Content-Type" = "application/json"
            }

            $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body

            Write-Output "Pipeline B triggered successfully. Run ID: $($response.id)"
        pwsh: true
