trigger:
  - main

pool: myagent
resources:
  pipelines:
    - pipeline: gitleak
      source: gitleak
      trigger:
        branches:
          include:
            - main

steps:
  - download: gitleak
    artifact: gitleaks-report # Download the 'report' artifact produced by the gitleak pipeline

  - script: |
      echo "Processing gitleaks report..."
      type $(Pipeline.Workspace)/report/gitleaks-report.json
