trigger:
  branches:
    include:
      - main

pool: Azure Pipelines

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: "specific"
      project: "gitleak"
      pipeline: "gitleak"
      artifact: "RepoBArtifact"
