trigger:
  - main

pool: myagent
resources:
  pipelines:
    - pipeline: gitleak
      source: gitleak
      trigger:
        branches:
          include:
            - main

steps:
  - download: gitleak
    artifact: gitleaks-report

  - script: |
      echo "Processing gitleaks report..."
