trigger:
  - main

resources:
  pipelines:
    - pipeline: gitleak
      source: devopsteam
      trigger:
        branches:
          include:
            - main

steps:
  - download: gitleak
    artifact: gitleaks-report

  - script: |
      echo "Processing gitleaks report.."
